name: Slack DND Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
    - name: Build with py2app and compress with tar
      run: |
        python3 setup.py py2app
        tar -czvf Slack.DND.tar.gz --directory=./dist/ .
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      if: "!contains(github.ref_name, 'main')"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
    - name: Create Release
      id: create_main_release
      uses: actions/create-release@v1
      if: "contains(github.ref_name, 'main')"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Slack.DND.tar.gz
        asset_name: Slack.DND.tar.gz
        asset_content_type: application/tar.gz
